var nlMessages = {
  "addlayer.applybuttontext": "Pas toe",
  "addlayer.applybuttontitle": "Pas toe",
  "addlayer.dropzonehelp": "Sleep hier een KML, GPX of GeoJSON bestand, of klik om er een te selecteren.",
  "addlayer.dropzonelabel": "Bestand",
  "addlayer.fillcolorlabel": "Vul kleur",
  "addlayer.menutext": "Upload",
  "addlayer.menutitle": "Voeg laag toe",
  "addlayer.modaltitle": "Upload laag",
  "addlayer.strokecolorlabel": "Lijn kleur",
  "addwmslayermodal.connectbutton": "Verbind",
  "addwmslayermodal.errormsg": "Fout bij ophalen GetCapabilities. {msg}",
  "addwmslayermodal.inputfieldlabel": "{serviceType} Url",
  "addwmslayermodal.title": "Voeg toe",
  "bookmarks.dropdowntext": "Bladwijzers",
  "chart.count": "Aantal features",
  "edit.attributeslabel": "Attributen (komma gescheiden namen)",
  "edit.createbuttontext": "Maak",
  "edit.createbuttontitle": "Maak lege laag",
  "edit.createlayermodaltitle": "Maak lege laag",
  "edit.disable": "Schakel wijzig modus uit",
  "edit.enable": "Schakel wijzig modus in",
  "edit.fillcolorlabel": "Vul kleur",
  "edit.geometrytypelabel": "Geometrie type",
  "edit.layerlabel": "Laag",
  "edit.layernamelabel": "Laagnaam",
  "edit.linegeomtype": "Lijn",
  "edit.newfeaturemodaltitle": "Attributen voor een nieuw feature",
  "edit.nolayer": "Geen",
  "edit.nolayererror": "Geen wijzigbare laag is beschikbaar. Maak een nieuwe om te kunnen wijzigen.",
  "edit.okbuttontext": "Ok",
  "edit.okbuttontitle": "Stel attributen van feature in",
  "edit.pointgeomtype": "Punt",
  "edit.polygeomtype": "Polygoon",
  "edit.strokecolorlabel": "Lijn kleur",
  "editpopup.errormsg": "Fout bij opslaan van dit feature. {msg}",
  "editpopup.save": "Opslaan",
  "editpopup.updatemsg": "Fout bij bijwerken van de attributen van het feature middels WFS-T.",
  "featuretable.clearbuttontext": "Wissen",
  "featuretable.clearbuttontitle": "Wis selectie",
  "featuretable.filterbuttontext": "Filter resultaten gebaseerd op jouw criteria",
  "featuretable.filterhelptext": "ATTRIBUUT == \"Waarde\"",
  "featuretable.filterlabel": "Filter",
  "featuretable.filterplaceholder": "Type filter expressie",
  "featuretable.layerlabel": "Laag",
  "featuretable.movebuttontext": "Naar boven",
  "featuretable.movebuttontitle": "Verplaats geselecteerde features naar boven",
  "featuretable.onlyselected": "Toon alleen geselecteerde features",
  "featuretable.zoombuttontext": "Zoom",
  "featuretable.zoombuttontitle": "Zoom naar selectie",
  "filtereditor.filterhelptext": "ATTRIBUUT == \"Waarde\"",
  "filtereditor.filterlabel": "Filter",
  "filtereditor.filterplaceholder": "Type filter expressie ....",
  "filtermodal.addfiltertext": "Voeg toe",
  "filtermodal.inputlabel": "Tekst om features in laag te filteren",
  "filtermodal.removefiltertext": "Verwijder",
  "filtermodal.title": "Filters voor laag {layer}",
  "geocoding.placeholder": "Zoek op plaatsnaam...",
  "geocodingresults.noresults": "Geen resultaten gevonden",
  "geolocation.buttontitle": "Geolocatie",
  "geolocation.error": "Fout bij het ophalen van geolocatie, details: {details}",
  "homebutton.buttontitle": "Home",
  "imageexport.buttontext": "Exporteer",
  "imageexport.buttontitle": "Exporteer als plaatje",
  "infopopup.nofeatures": "Geen features op deze locatie",
  "infopopup.nulltext": "NULL",
  "labeleditor.attributelabel": "Attribuut",
  "labeleditor.fillcolorlabel": "Tekstkleur",
  "labeleditor.sizelabel": "Tekstgrootte",
  "labelmodal.applybutton": "Pas toe",
  "labelmodal.clearbutton": "Wis",
  "labelmodal.title": "Label voor laag {layer}",
  "layerlist.addlayertext": "Voeg laag toe",
  "layerlist.addlayertitle": "Voeg lagen toe",
  "layerlist.layertitle": "Lagen",
  "layerlistitem.baselayergrouplabel": "Selecteer ondergrond laag",
  "layerlistitem.basemapstitle": "Ondergrond Laag",
  "layerlistitem.downloadtitle": "Download laag",
  "layerlistitem.edittitle": "Wijzig laag",
  "layerlistitem.filtertitle": "Filter laag",
  "layerlistitem.labeltitle": "Label laag",
  "layerlistitem.layervisibilitylabel": "Laag zichtbaarheid",
  "layerlistitem.movedowntitle": "Verplaats naar beneden",
  "layerlistitem.moveuptitle": "Verplaats naar boven",
  "layerlistitem.opacitylabel": "Laag ondoorzichtigheid",
  "layerlistitem.removetitle": "Verwijder",
  "layerlistitem.stylingtitle": "Wijzig kaartstijl",
  "layerlistitem.zoomtotitle": "Zoom naar laag",
  "measure.cleartext": "Verwijder metingen",
  "measure.dropdowntext": "Meet",
  "measure.measureareatext": "Oppervlakte",
  "measure.measuredistancetext": "Afstand",
  "playback.dateinputlabel": "Datum kiezer",
  "playback.rangeinputlabel": "Schuif input voor het veranderen van de datum",
  "qgislegend.buttontitle": "Legenda",
  "qgisprint.error": "Fout bij het genereren van PDF, details: {details}",
  "qgisprint.modaltitle": "Print kaart",
  "qgisprint.printbuttontext": "Print",
  "qgisprint.printbuttontitle": "Print kaart",
  "qgisprint.printmenutext": "Print",
  "qgisprint.resolutionlabel": "Resolutie",
  "qgisprint.waittext": "Genereren van PDF ...",
  "querybuilder.addbuttontext": "Voeg toe",
  "querybuilder.addbuttontitle": "Voeg toe aan huidige selectie",
  "querybuilder.filterbuttontext": "Geselecteerde items gebaseerd op jouw criteria",
  "querybuilder.filterhelptext": "ATTRIBUUT == \"Waarde\"",
  "querybuilder.filterlabel": "Filter",
  "querybuilder.filterplaceholder": "Type expressie ....",
  "querybuilder.layerlabel": "Laag",
  "querybuilder.newbuttontext": "Nieuw",
  "querybuilder.newbuttontitle": "Nieuwe selectie",
  "querybuilder.selectintext": "Selecteer",
  "querybuilder.selectintitle": "Selecteer in huidigie selectie",
  "ruleeditor.filltitle": "Vulling",
  "ruleeditor.filtertitle": "Filter",
  "ruleeditor.labeltitle": "Label",
  "ruleeditor.stroketitle": "Lijn",
  "select.menubuttontext": "Selectie",
  "select.rectangletext": "Selecteer d.m.v. rechthoek",
  "strokeeditor.strokecolorlabel": "Lijnkleur",
  "strokeeditor.strokewidthlabel": "Lijndikte",
  "stylemodal.addrulebutton": "Voeg nieuwe regel toe",
  "stylemodal.applybutton": "Pas toe",
  "stylemodal.removerulebutton": "Verwijder geselecteerde regel",
  "stylemodal.rulelabel": "Selecteer Regel:",
  "stylemodal.title": "Wijzig laag stijl voor: {layer}",
  "wfst.deletefeature": "Verwijder",
  "wfst.deletemsg": "Er was een probleem met het verwijderen.",
  "wfst.drawfeature": "Teken",
  "wfst.errormsg": "Fout bij het opslaan van dit feature middels GeoServer WFS-T. {msg}",
  "wfst.layerlabel": "Laag",
  "wfst.modifyfeature": "Wijzig / Selecteer"
};

export default nlMessages;
