var nlMessages = {
  "addlayer.applybuttontext": "Pas toe",
  "addlayer.applybuttontitle": "Pas toe",
  "addlayer.closebuttontext": "Sluit",
  "addlayer.closebuttontitle": "Sluit scherm",
  "addlayer.dropzonehelp": "Sleep hier een KML, GPX of GeoJSON bestand, of klik om er een te selecteren.",
  "addlayer.dropzonelabel": "Bestand",
  "addlayer.errormsg": "Er is een fout opgetreden bij het lezen van het bestand. ({msg})",
  "addlayer.fillcolorlabel": "Vul kleur",
  "addlayer.menutext": "Upload",
  "addlayer.menutitle": "Voeg laag toe",
  "addlayer.modaltitle": "Upload laag",
  "addlayer.strokecolorlabel": "Lijn kleur",
  "addlayer.waitmsg": "Even wachten a.u.b. ...",
  "addwmslayermodal.addbutton": "Voeg toe",
  "addwmslayermodal.addserverbutton": "Voeg toe",
  "addwmslayermodal.closebutton": "Sluit",
  "addwmslayermodal.connectbutton": "Verbind",
  "addwmslayermodal.corserror": "Kon niet verbinden met de server. Controleer dat de server online is en dat CORS aan staat.",
  "addwmslayermodal.errormsg": "Fout. {msg}",
  "addwmslayermodal.filtertitle": "Filter",
  "addwmslayermodal.inputfieldlabel": "{serviceType} Url",
  "addwmslayermodal.newservermodaltitle": "Voeg server toe",
  "addwmslayermodal.newservername": "Naam",
  "addwmslayermodal.newserverurl": "URL",
  "addwmslayermodal.nolayertitle": "Geen Titel",
  "addwmslayermodal.refresh": "Ververs Lagen",
  "addwmslayermodal.servertypelabel": "Type",
  "addwmslayermodal.title": "Voeg toe",
  "basemapmodal.closebutton": "Sluit",
  "basemapmodal.title": "Selecteer een achtergrondkaart",
  "basemapselector.buttontext": "Achtergrondkaart",
  "bookmarks.dropdowntext": "Bladwijzers",
  "chart.count": "Aantal features",
  "edit.attributeslabel": "Attributen (komma gescheiden namen)",
  "edit.closebuttontext": "Sluit",
  "edit.closebuttontitle": "Sluit scherm",
  "edit.createbuttontext": "Maak",
  "edit.createbuttontitle": "Maak lege laag",
  "edit.createlayermodaltitle": "Maak lege laag",
  "edit.disable": "Schakel uit",
  "edit.disabletitle": "Schakel wijzig modus uit",
  "edit.enable": "Schakel in",
  "edit.enabletitle": "Schakel wijzig modus in",
  "edit.fillcolorlabel": "Vul kleur",
  "edit.geometrytypelabel": "Geometrie type",
  "edit.layerlabel": "Laag",
  "edit.layernamelabel": "Laagnaam",
  "edit.linegeomtype": "Lijn",
  "edit.newfeaturemodaltitle": "Attributen voor een nieuw feature",
  "edit.newlayer": "Nieuw",
  "edit.newlayertitle": "Maak nieuwe laag",
  "edit.okbuttontext": "Ok",
  "edit.okbuttontitle": "Stel attributen van feature in",
  "edit.pointgeomtype": "Punt",
  "edit.polygeomtype": "Polygoon",
  "edit.strokecolorlabel": "Lijn kleur",
  "editpopup.deletefeature": "Verwijder",
  "editpopup.deletefeaturetitle": "Verwijder het geselecteerde feature",
  "editpopup.deletemsg": "Er was een fout bij het verwijderen van het feature.",
  "editpopup.errormsg": "Fout bij opslaan van dit feature. {msg}",
  "editpopup.save": "Opslaan",
  "editpopup.savetitle": "Sla gewijzigde attributen op",
  "editpopup.updatemsg": "Fout bij bijwerken van de attributen van het feature middels WFS-T.",
  "featuretable.clearbuttontext": "Wissen",
  "featuretable.clearbuttontitle": "Wis selectie",
  "featuretable.errormsg": "Er is een fout opgetreden bij het filteren van de features. ({msg})",
  "featuretable.filterbuttontext": "Filter resultaten gebaseerd op jouw criteria",
  "featuretable.filterhelptext": "ATTRIBUUT == \"Waarde\"",
  "featuretable.filterlabel": "Filter",
  "featuretable.filterplaceholder": "Type filter expressie",
  "featuretable.layerlabel": "Laag",
  "featuretable.loaderrormsg": "Er is een fout opgetreden bij het laden van de features. ({msg})",
  "featuretable.nodatamsg": "Er zijn nog geen lagen met vector data, dus er is geen data om weer te geven in de tabel. Als er een laag met vector data wordt toegevoegd, zal de data hier zichtbaar worden.",
  "featuretable.onlyselected": "Toon alleen geselecteerde features",
  "featuretable.optionslabel": "Opties",
  "featuretable.zoombuttontext": "Zoom",
  "featuretable.zoombuttontitle": "Zoom naar selectie",
  "filleditor.fillcolorlabel": "Fill color",
  "filtereditor.errortext": "Ongeldig filter, gebruik bijvoorbeeld ATTRIBUUT == \"Waarde\"",
  "filtereditor.filterlabel": "Filter",
  "filtereditor.filterplaceholder": "Type expressie ....",
  "filterhelp.example1description": "Alle features met een inwoneraantal groter dan 100000",
  "filterhelp.example1filter": "population > 100000",
  "filterhelp.example2description": "Alle Britse kolonies die niet in Europa liggen",
  "filterhelp.example2filter": "sovereignt == \"United Kingdom\" and not (subregion like \"Europe\")",
  "filterhelp.exampletext": "Voorbeelden:",
  "filterhelp.generalsection": "Expressies kunnen attribuut namen, strings, nummers, and operatoren bevatten. Attribuut namen kunnen omringd worden door enkele quotes (') om duidelijkheid te geven. Strings moeten omringd worden door dubbele quotes (\"). Nummers en operatoren worden niet omringd.",
  "filterhelp.introtextprefix": "Type in",
  "filterhelp.introtextsuffix": "een filter expressie om de zoekopdracht te beperken tot een of meer attributen.",
  "filterhelp.operator1": "a == a",
  "filterhelp.operator10": "e or f",
  "filterhelp.operator10description": "Expressie e of f is waar",
  "filterhelp.operator11": "not e",
  "filterhelp.operator11description": "Geeft alle resultaten terug die niet expressie e matchen",
  "filterhelp.operator1description": "a is exact gelijk aan b",
  "filterhelp.operator2": "a != a",
  "filterhelp.operator2description": "a is niet gelijk aan b",
  "filterhelp.operator3": "a < a",
  "filterhelp.operator3description": "a is kleiner dan b",
  "filterhelp.operator4": "a <= b",
  "filterhelp.operator4description": "a is kleiner dan of gelijk aan b",
  "filterhelp.operator5": "a > b",
  "filterhelp.operator5description": "a is groter dan b",
  "filterhelp.operator6": "a >= b",
  "filterhelp.operator6description": "a is groter dan of gelijk aan b",
  "filterhelp.operator7": "a like b",
  "filterhelp.operator7description": "b bevat a (hoofdletter ongevoelig)",
  "filterhelp.operator8": "a in (x,y,z)",
  "filterhelp.operator8description": "a is gelijk aan 1 of meerdere waardes uit de lijst x,y,z",
  "filterhelp.operator9": "e and f",
  "filterhelp.operator9description": "Matcht zowel expressies e als f",
  "filterhelp.operatortext": "Ondersteunde operatoren zijn:",
  "filterhelp.parantheses": "Elke expressie mag omringd worden door haakjes voor de duidelijkheid (bijv. wanneer ands en ors gecombineerd worden).",
  "filtermodal.addfiltertext": "Voeg toe",
  "filtermodal.closebutton": "Sluit",
  "filtermodal.errortext": "Ongeldig filter, gebruik bijvoorbeeld foo == \"Bar\"",
  "filtermodal.inputlabel": "Tekst om features in laag te filteren",
  "filtermodal.removefiltertext": "Verwijder",
  "filtermodal.title": "Filters voor laag {layer}",
  "geocoding.placeholder": "Zoek op plaatsnaam...",
  "geocodingresults.noresults": "Geen resultaten gevonden",
  "geolocation.buttontitle": "Geolocatie",
  "geolocation.error": "Fout bij het ophalen van geolocatie, details: {details}",
  "geolocation.trackingtitle": "Tracking",
  "globe.globetext": "Schakel naar wereldbol (3D)",
  "globe.maptext": "Schakel naar kaart (2D)",
  "homebutton.buttontitle": "Thuis",
  "imageexport.buttontext": "Exporteer",
  "imageexport.buttontitle": "Exporteer als plaatje",
  "infopopup.nametext": "Naam",
  "infopopup.nofeatures": "Geen features op deze locatie",
  "infopopup.nulltext": "NULL",
  "infopopup.valuetext": "Waarde",
  "labeleditor.attributelabel": "Attribuut",
  "labeleditor.emptytext": "Selecteer een attribuut",
  "labeleditor.fillcolorlabel": "Tekstkleur",
  "labeleditor.sizelabel": "Tekstgrootte",
  "labelmodal.applybutton": "Pas toe",
  "labelmodal.clearbutton": "Wis",
  "labelmodal.closebutton": "Sluit",
  "labelmodal.title": "Label voor laag {layer}",
  "layerlist.addbasemaptext": "Achtergrond kaart",
  "layerlist.addlayertext": "Voeg laag toe",
  "layerlist.addlayertitle": "Voeg lagen toe",
  "layerlist.closebutton": "Sluit",
  "layerlist.downloadbuttonlabel": "Download laag",
  "layerlist.editbuttonlabel": "Wijzig laag",
  "layerlist.errormsg": "Er is een fout opgetreden bij het ophalen van kaart tegels.",
  "layerlist.filterbuttonlabel": "Filter laag",
  "layerlist.labelbuttonlabel": "Wijzig laag label",
  "layerlist.layertitle": "Lagen",
  "layerlist.removebuttonlabel": "Verwijder laag",
  "layerlist.stylingbuttonlabel": "Wijzig laag stijl",
  "layerlist.tablebuttonlabel": "Toon tabel",
  "layerlist.tablemodaltitle": "Tabel",
  "layerlist.zoombuttonlabel": "Zoom naar laag",
  "layerselector.emptytext": "Selecteer een laag",
  "layerselector.labeltext": "Laag",
  "legend.emptyheader": "Geen legenda beschikbaar",
  "legend.header": "Legenda",
  "login.buttontext": "Log in",
  "login.logouttext": "Log uit",
  "loginmodal.closebutton": "Sluit",
  "loginmodal.errormsg": "Er is een fout opgetreden bij de communicatie met GeoServer, details: {details}",
  "loginmodal.helptext": "Gebruik de GeoServer inloggegevens.",
  "loginmodal.invalidcredentialsmsg": "Ongeldigde combinatie",
  "loginmodal.loginbutton": "Log in",
  "loginmodal.passwordlabel": "Wachtwoord",
  "loginmodal.title": "Log in",
  "loginmodal.userlabel": "Gebruikersnaam",
  "mapconfig.loadfailure": "Er is een fout opgetreden bij het laden van de kaart uit de local storage van de browser.",
  "mapconfig.loadsuccess": "Kaart is succesvol geladen uit de local storage van de browser.",
  "mapconfig.loadtext": "Laad",
  "mapconfig.loadtitle": "Laad kaart configuratie vanuit local storage",
  "mapconfig.savefailure": "Er is een fout opgetreden bij het opslaan van de kaart in de local storage van de browser.",
  "mapconfig.savesuccess": "Kaart is succesvol opgeslagen in de local storage van de browser.",
  "mapconfig.savetext": "Opslaan",
  "mapconfig.savetitle": "Sla de kaart configuratie op in local storage",
  "measure.cleartext": "Verwijder metingen",
  "measure.dropdowntext": "Meet",
  "measure.dropdowntitle": "Meeet afstand en oppervlakte op de kaart",
  "measure.measureareatext": "Oppervlakte",
  "measure.measuredistancetext": "Afstand",
  "navigation.buttontext": "Navigatie",
  "navigation.buttontitle": "Switch naar kaart navigatie (verschuif en zoom)",
  "pointsymbolizereditor.externalgraphic": "URL",
  "pointsymbolizereditor.filllabel": "Vulling",
  "pointsymbolizereditor.opacity": "Opaciteit",
  "pointsymbolizereditor.strokelabel": "Lijn",
  "pointsymbolizereditor.symbolrotation": "Rotatie",
  "pointsymbolizereditor.symbolsize": "Grootte",
  "pointsymbolizereditor.symboltype": "Symbool",
  "polygonsymbolizereditor.filllabel": "Vulling",
  "polygonsymbolizereditor.strokelabel": "Lijn",
  "qgislegend.buttontitle": "Legenda",
  "qgisprint.closebuttontext": "Sluit",
  "qgisprint.error": "Fout bij het genereren van PDF, details: {details}",
  "qgisprint.modaltitle": "Print kaart",
  "qgisprint.printbuttontext": "Print",
  "qgisprint.printbuttontitle": "Print kaart",
  "qgisprint.printmenutext": "Print",
  "qgisprint.resolutionlabel": "Resolutie",
  "querybuilder.addbuttontext": "Voeg toe",
  "querybuilder.addbuttontitle": "Voeg toe aan huidige selectie",
  "querybuilder.filterbuttontext": "Geselecteerde items gebaseerd op jouw criteria",
  "querybuilder.filterhelptext": "ATTRIBUUT == \"Waarde\"",
  "querybuilder.filterlabel": "Filter",
  "querybuilder.filterplaceholder": "Type expressie ....",
  "querybuilder.layerlabel": "Laag",
  "querybuilder.newbuttontext": "Nieuw",
  "querybuilder.newbuttontitle": "Nieuwe selectie",
  "querybuilder.selectintext": "Selecteer",
  "querybuilder.selectintitle": "Selecteer in huidigie selectie",
  "rotate.rotatetitle": "Reset rotation",
  "ruleeditor.filltitle": "Vulling",
  "ruleeditor.filtertitle": "Filter",
  "ruleeditor.labeltitle": "Label",
  "ruleeditor.stroketitle": "Lijn",
  "select.menubuttontext": "Selectie",
  "select.menubuttontitle": "Selecteer features middels rechthoek",
  "strokeeditor.strokecolorlabel": "Lijnkleur",
  "strokeeditor.strokewidthlabel": "Lijndikte",
  "stylemodal.addrulebutton": "Voeg nieuwe regel toe",
  "stylemodal.applybutton": "Pas toe",
  "stylemodal.removerulebutton": "Verwijder geselecteerde regel",
  "stylemodal.rulelabel": "Selecteer Regel:",
  "stylemodal.title": "Wijzig laag stijl voor: {layer}",
  "wfst.deletefeature": "Verwijder",
  "wfst.deletemsg": "Er was een probleem met het verwijderen.",
  "wfst.drawfeature": "Teken",
  "wfst.errormsg": "Fout bij het opslaan van dit feature middels GeoServer WFS-T. {msg}",
  "wfst.layerlabel": "Laag",
  "wfst.modifyfeature": "Wijzig / Selecteer",
  "zoom.zoomintitle": "Zoom in",
  "zoom.zoomouttitle": "Zoom uit",
  "zoomtolatlon.buttontext": "Lat/Lon",
  "zoomtolatlon.buttontitle": "Zoom naar WGS84 coordinaten",
  "zoomtolatlon.closebuttontext": "Sluit",
  "zoomtolatlon.closebuttontitle": "Sluit scherm",
  "zoomtolatlon.ddtitle": "Decimale graden (DD)",
  "zoomtolatlon.degreeslabel": "D",
  "zoomtolatlon.directionlabel": "Halfrond",
  "zoomtolatlon.dmstitle": "Graden minuten seconden (DMS)",
  "zoomtolatlon.east": "Oost",
  "zoomtolatlon.latitudelabel": "Breedtegraad",
  "zoomtolatlon.longitudelabel": "Lengtegraag",
  "zoomtolatlon.minuteslabel": "M",
  "zoomtolatlon.modaltitle": "Zoom naar breedtegraad lengtegraad",
  "zoomtolatlon.north": "Noord",
  "zoomtolatlon.secondslabel": "S",
  "zoomtolatlon.south": "Zuid",
  "zoomtolatlon.west": "West",
  "zoomtolatlon.zoombuttontext": "Zoom",
  "zoomtolatlon.zoombuttontitle": "Zoom naar breedtegraad / lengtegraad"
};

export default nlMessages;
